# Generated by Django 4.1.1 on 2022-12-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banars')),
            ],
        ),
        migrations.CreateModel(
            name='CatCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='CatCourses/%y/%m/%d')),
                ('star', models.BooleanField(blank=True, default=False, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='teacher/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.college')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('video', models.FileField(upload_to='courses/%y/%m/%d')),
                ('CatCourses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.catcourses')),
            ],
        ),
        migrations.AddField(
            model_name='catcourses',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.year'),
        ),
    ]
