# Generated by Django 4.1.1 on 2022-12-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totlaPrice', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('userCart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userCart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='catcourses',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catcourses',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ye', to='course.year'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('Courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='course.catcourses')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItemWithCart', to='course.cart')),
                ('userCartItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCartItem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
