# Generated by Django 4.1.1 on 2022-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_catcourses_image_alter_catcourses_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcourses',
            name='image',
            field=models.ImageField(default=1, upload_to='CatCourses/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
