# Generated by Django 4.1.1 on 2022-12-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_catcourses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcourses',
            name='image',
            field=models.FileField(upload_to='CatCourses/%y/%m/%d'),
        ),
    ]
