# Generated by Django 4.1.1 on 2022-12-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_catcourses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcourses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CatCourses/%y/%m/%d'),
        ),
    ]
