# Generated by Django 4.1.1 on 2022-12-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_catcourses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
