# Generated by Django 4.1.1 on 2022-12-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_cart_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='CatCourses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.catcourses'),
        ),
    ]
