# Generated by Django 4.1.1 on 2022-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catcourses',
            name='cartIcon',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
