# Generated by Django 4.1.1 on 2022-12-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_catcourses_mycourseicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='catcourses',
            name='myCourseIcon',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
