# Generated by Django 4.1.1 on 2023-01-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_catcourses_mycourseicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='payy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
