# Generated by Django 4.1.1 on 2022-12-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_alter_catcourses_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='mony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.cart')),
            ],
        ),
    ]
