# Generated by Django 4.1.1 on 2022-12-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mony',
            name='serial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
